'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Language_French
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SchoolMosaic.Server.Language.French", GetType(Language_French).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à F&amp;ermer la base.
        '''</summary>
        Friend Shared ReadOnly Property CloseBaseMenu() As String
            Get
                Return ResourceManager.GetString("CloseBaseMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Poste.
        '''</summary>
        Friend Shared ReadOnly Property ComputerColumn() As String
            Get
                Return ResourceManager.GetString("ComputerColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration.
        '''</summary>
        Friend Shared ReadOnly Property ConfigTab() As String
            Get
                Return ResourceManager.GetString("ConfigTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pour modifier la configuration, vous devez entrer un mot de passe administrateur.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationBanner() As String
            Get
                Return ResourceManager.GetString("ConfigurationBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Heure de connexion.
        '''</summary>
        Friend Shared ReadOnly Property DateTimeColumn() As String
            Get
                Return ResourceManager.GetString("DateTimeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Quitter.
        '''</summary>
        Friend Shared ReadOnly Property ExitMenu() As String
            Get
                Return ResourceManager.GetString("ExitMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Fichier.
        '''</summary>
        Friend Shared ReadOnly Property FileMenu() As String
            Get
                Return ResourceManager.GetString("FileMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Modifier....
        '''</summary>
        Friend Shared ReadOnly Property ModifyButton() As String
            Get
                Return ResourceManager.GetString("ModifyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Nouvelle base....
        '''</summary>
        Friend Shared ReadOnly Property NewBaseMenu() As String
            Get
                Return ResourceManager.GetString("NewBaseMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Ouvrir la base....
        '''</summary>
        Friend Shared ReadOnly Property OpenBaseMenu() As String
            Get
                Return ResourceManager.GetString("OpenBaseMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aperçu.
        '''</summary>
        Friend Shared ReadOnly Property OverviewTab() As String
            Get
                Return ResourceManager.GetString("OverviewTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom d&apos;affichage du serveur :.
        '''</summary>
        Friend Shared ReadOnly Property ServerDisplayNameLabel() As String
            Get
                Return ResourceManager.GetString("ServerDisplayNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Serveur.
        '''</summary>
        Friend Shared ReadOnly Property ServerMenu() As String
            Get
                Return ResourceManager.GetString("ServerMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Port :.
        '''</summary>
        Friend Shared ReadOnly Property ServerPortLabel() As String
            Get
                Return ResourceManager.GetString("ServerPortLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Server éteint.
        '''</summary>
        Friend Shared ReadOnly Property ServerStatusOff() As String
            Get
                Return ResourceManager.GetString("ServerStatusOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Serveur en marche.
        '''</summary>
        Friend Shared ReadOnly Property ServerStatusOn() As String
            Get
                Return ResourceManager.GetString("ServerStatusOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Démarrer.
        '''</summary>
        Friend Shared ReadOnly Property StartMenu() As String
            Get
                Return ResourceManager.GetString("StartMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Arrêter.
        '''</summary>
        Friend Shared ReadOnly Property StopMenu() As String
            Get
                Return ResourceManager.GetString("StopMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property UsernameColumn() As String
            Get
                Return ResourceManager.GetString("UsernameColumn", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
